name: 'beam'
description: 'Your personal GitHub IssueOps Binary Electronic Assistant Machine'

branding:
  icon: loader
  color: white

inputs:
  bot-name:
    required: true
    description: 'The action will react to commands issued for this name'
    default: 'beam'
  bot-reaction:
    required: true
    description: 'The reaction that will be used to mark processed comments'
    default: '+1'
  token:
    required: true
    description: 'Your GitHub token'
    default: ${{ github.token }}
  state-branch:
    required: false
    description: 'A branch used to keep action state'
    default: 'beam-state'
  ai-enabled:
    required: false
    description: 'If you want to use AI features'
    default: 'false'
  openai-api-key:
    required: false
    description: 'The OpenAI API Key if AI is enabled'
runs:
  using: 'node16'
  main: 'dist/index.js'
