name: Test

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  discussions: read
  issues: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Beam test
        if: ${{ github.event.issue.pull_request }}
        uses: ./
