name: Test

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  discussions: write
  issues: read
  pull-requests: write
  deployments: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Beam test
        if: ${{ github.event.issue.pull_request }}
        uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          ai-enabled: true
          app-id: ${{ secrets.GHA_APP_ID }}
          app-private-key: ${{ secrets.GHA_APP_PRIVATE_KEY }}
          app-installation-id: ${{ secrets.GHA_APP_INSTALLATION_ID }}
